name: Deploy Lambda Functions

on:
  push:
    paths:
      - 'src/**'
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install zip tool
        uses: nontudor/action-zip@v1

      - name: Create Zip file for Lambda function
        run: cd src && zip -r code.zip

      - name: AWS CLI v2
        uses: inehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code \
              --function-name arn:aws:lambda:us-east-1:226375610017:function:TestCICDFunction \
              --zip-file fileb://src/code.zip"
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
