name: Deploy Lambda Functions

on:
  push:
    branches:
      - main          # <- dispara apenas na main
    paths:
      - 'lambda-functions/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install zip tool
        run: sudo apt-get install -y zip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy only changed Lambda functions
        run: |
          CHANGED_DIRS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | \
            grep '^lambda-functions/' | \
            cut -d'/' -f2 | \
            sort -u)

          if [ -z "$CHANGED_DIRS" ]; then
            echo "Nenhuma função Lambda
