name: Deploy Lambda Function on src changes

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install zip
        run: sudo apt-get install -y zip

      - name: Zip Lambda code
        run: |
          cd src
          zip -r ../code.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:us-east-1:226375610017:function:TestCICDFunction \
            --zip-file fileb://code.zip